AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - db/schema.rb
    - bin/**
    - db/seeds.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - config/puma.rb
    - config/environments/*
    - config/initializers/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*